function EEG = lix_getback_onlineref(EEG, brainmodel, online_ref)

% brainmodel = 'MNI';
% online_ref
% offline_ref
nchan = size(EEG.data,1);
fcz = nchan+1;

if strcmpi(brainmodel, 'mni') && strcmpi(online_ref, 'fcz')
	elc_dir = dirname(which('standard_1005.elc'));
	EEG=pop_chanedit(EEG, ...
		'lookup', elc_dir, ...
		'append',nchan, ...
		'changefield',{fcz 'labels' 'FCz'}, ...
		'lookup',elc_dir,...
		'setref',{['1:',int2str(fcz)] 'FCz'});
	EEG = pop_reref( EEG, [], ...
		'refloc',struct('labels',{'FCz'},...
		'type',{''},...
		'theta',{-89.2133},...
		'radius',{0.095376},...
		'X',{0.3761},...
		'Y',{27.39},...
		'Z',{88.668},...
		'sph_theta',{89.2133},...
		'sph_phi',{72.8323},...
		'sph_radius',{92.8028},...
		'urchan',{fcz},...
		'ref',{'FCz'},...
		'datachan',{0}));
end
EEG = eeg_checkset( EEG );