function EEG = runDipFit(EEG, params)

hdmfileDir = params.hdmfileDir;
mrifileDir = params.mrifileDir;
chanfileDir = params.chanfileDir;
TRANS = params.TRANS;
MODEL = params.MODEL;
RV = params.RV;
nbcomp = size(EEG.icaact, 1);
EEG = pop_dipfit_settings( EEG, ...
		     'hdmfile', hdmfileDir, ...
		     'coordformat', MODEL, ...
		     'mrifile', mrifileDir, ...
		     'chanfile', chanfileDir, ...
		     'coord_transform', TRANS, ...
		     'chansel', [1:nbcomp] );
EEG = pop_dipfit_gridsearch(EEG, [1:nbcomp] , ...
 			   [-85:17:85], [-85:17:85], [0:17:85], RV);
EEG = pop_multifit( EEG, [1:nbcomp] , ...
		'threshold', RV*100, ...
		'plotopt', {'normlen' 'on'});
EEG = eeg_checkset( EEG );