%% line plot for spectral time series
outdir = '~/Desktop/image/';
if ~exist(outdir, 'dir'); mkdir(outdir); end
theta = [5.5, 7.5];
alpha = [10.5, 12];
beta = [18, 20];
band = 'theta';
chans = chanlabels;
%%
if strcmp(band, 'theta') || strcmp(band, 'beta')
    chan = {'F3', 'Fz', 'F4', ...
            'FC3', 'FCz', 'FC4', ...
            'C3', 'Cz', 'C4', ...
            'CP3', 'CPz', 'CP4'};
    % chan = {'Cz'};
elseif strcmp(band, 'alpha')
    chan = {'PO7', 'PO8', 'PO3', 'PO4', 'POz', ...
            'Oz', 'O1', 'O2'};
end
WIDTH = 20;
HEIGHT = 40;
LINEWIDTH = 2;
LEGEND = {'high', 'medium', 'neutral'};
YLIM = [-1, 4];
for i = 1:numel(chan)
    roi = eval(band);
    TITLE = {sprintf('%s %s of Adults', chan{i}, band),...
             sprintf('%s %s of Adolescents', chan{i}, band)};
    f = dsearchn(fre', roi');
    c = find(ismember(chans, chan{i}));
    dataSubset = cellfun(@(x) {squeeze(mean(x(f(1):f(2), :, c, :), 1))}, ...
                         data);
    % loYLIM = floor(min(min(cell2mat(dataSubset)))*0.4);
    % hiYLIM = floor(max(max(cell2mat(dataSubset)))*0.4);
    % YLIM = [loYLIM, hiYLIM];
    %% plotcurve
    std_plotcurve( times, dataSubset, ...
                   'datatype', 'spec', ...
                   'titles', TITLE, ...
                   'plotgroups', 'apart', ...
                   'plotconditions', 'together', ...
                   'legend', 'on', ...
                   'plotdiff', 'off', ...
                   'plotstderr', 'off', ...
                   'figure', 'on', ...
                   'plotsubjects', 'off',...
                   'ylim', YLIM);
    set(gcf, 'Color', 'w', ...
             'PaperUnits', 'centimeters', ...
             'PaperPositionMode', 'manual',...
             'PaperSize', [WIDTH, HEIGHT], ...
             'PaperPosition', [0 0 WIDTH HEIGHT]);
    hline = findobj(gcf, 'Type', 'Line');
    set(hline, 'LineWidth', LINEWIDTH);
    childf = get(gcf, 'Children');
    set(get(childf(1), 'ylabel'), 'string', 'ERSP (dB)', 'FontSize', 14);
    set(get(childf(2), 'ylabel'), 'string', 'ERSP (dB)', 'FontSize', 14);
    set(get(childf(2), 'xlabel'), 'string', '');
    set(get(childf(1), 'xlabel'), 'string', 'Time (ms)', 'FontSize', 14);
    set(get(childf(1), 'title'), 'FontSize', 16);
    set(get(childf(2), 'title'), 'FontSize', 16);
    set(childf, 'xlim', [-100 1000]);
    legend(childf(1), 'String', LEGEND, 'Location', 'NorthEast', ...
           'FontSize', 10);
    legend(childf(2), 'String', LEGEND, 'Location', 'NorthEast', ...
           'FontSize', 10);
    % save image
    outName = strcat('lineSpec_', band, '_', num2str(roi(1)), '-', ...
                     num2str(roi(2)), '_', chan{i});
    print(gcf, '-djpeg', '-cmyk', '-painters', ...
          fullfile(outdir, strcat(outName, '.jpg')));
    print(gcf, '-depsc', '-painters', ...
          fullfile(outdir, strcat(outName, '.eps')));
    save2pdf(fullfile(outdir, strcat(outName, '.pdf')), ...
             gcf, 600);
end

close all;
