% HN vs MN
% HN vs Neutral
% MN vs Neutral
% indir = '~/data/adolesvsadult/conditiondata/';
theta = [5.5, 7.5, 500, 600];
alpha = [10.5, 12, 850, 950];
beta = [18, 20, 500, 600];
band = {'theta', 'alpha', 'beta'};
TITLE = {'HN vs MN', 'HN vs Neutral', 'MN vs Neutral'};
YLABEL = {'Adults', 'Adolescents'};
WIDTH = 30;
HEIGHT = 10;

for i = 1
    figure('color', 'w', ...
           'nextplot', 'add', ...
           'PaperUnits', 'centimeters', ...
           'PaperPositionMode', 'manual', ...
           'papersize', [WIDTH, HEIGHT], ...
           'PaperPosition', [0 0 WIDTH HEIGHT]);
    roi = eval(band{i});
    f = dsearchn(freqs', roi(1:2)');
    t = dsearchn(times', roi(3:4)');
    dataSubset = ...
        cellfun(@(x) {squeeze(mean(mean(x(f(1):f(2), t(1):t(2), :, :), ...
                                        1), 2))}, data);
    % Adults: HN vs MN
    tmp = {dataSubset{1}; dataSubset{2}};
    [pcond, pgroup, pinter, statscond, statsgroup, statsinter] = ...
        std_stat(tmp, 'condstats', 'on', ...
                 'method', 'permutation', ...
                 'naccu', 500);
    subplot(231)
    topoplot(cell2mat(pcond), chanlocs, ...
             'style', 'map', ...
             'electrodes', 'on', ...
             'shading', 'flat', ...
             'whitebk', 'off');
    title(TITLE{1});
    ylabel(YLABEL{1});
    caxis([0 0.05]);
    % Adults: HN vs Neutral
    tmp = {dataSubset{1}; dataSubset{3}};
    [pcond, pgroup, pinter, statscond, statsgroup, statsinter] = ...
        std_stat(tmp, 'condstats', 'on', ...
                 'method', 'permutation', ...
                 'naccu', 500);
    subplot(232)
    topoplot(cell2mat(pcond), chanlocs, ...
             'style', 'map', ...
             'electrodes', 'on', ...
             'shading', 'flat', ...
             'whitebk', 'off');
    caxis([0 0.05]);
    title(TITLE{2});
    % Adults: MN vs Neutral
    tmp = {dataSubset{2}; dataSubset{3}};
    [pcond, pgroup, pinter, statscond, statsgroup, statsinter] = ...
        std_stat(tmp, 'condstats', 'on', ...
                 'method', 'permutation', ...
                 'naccu', 500);
    subplot(233)
    topoplot(cell2mat(pcond), chanlocs, ...
             'style', 'map', ...
             'electrodes', 'on', ...
             'shading', 'flat', ...
             'whitebk', 'off');
    title(TITLE{3});
    caxis([0 0.05]);
    % Adolescents: HN vs MN
    tmp = {dataSubset{4}; dataSubset{5}};
    [pcond, pgroup, pinter, statscond, statsgroup, statsinter] = ...
        std_stat(tmp, 'condstats', 'on', ...
                 'method', 'permutation', ...
                 'naccu', 500);
    subplot(234)
    topoplot(cell2mat(pcond), chanlocs, ...
             'style', 'map', ...
             'electrodes', 'on', ...
             'shading', 'flat', ...
             'whitebk', 'off');
    ylabel(YLABEL{2});
    caxis([0 0.05])
    % Adolescents: HN vs Neutral
    tmp = {dataSubset{4}; dataSubset{6}};
    [pcond, pgroup, pinter, statscond, statsgroup, statsinter] = ...
        std_stat(tmp, 'condstats', 'on', ...
                 'method', 'permutation', ...
                 'naccu', 500);
    subplot(235)
    topoplot(cell2mat(pcond), chanlocs, ...
             'style', 'map', ...
             'electrodes', 'on', ...
             'shading', 'flat', ...
             'whitebk', 'off');
    % Adolescents: MN vs Neutral
    tmp = {dataSubset{5}; dataSubset{6}};
    [pcond, pgroup, pinter, statscond, statsgroup, statsinter] = ...
        std_stat(tmp, 'condstats', 'on', ...
                 'method', 'permutation', ...
                 'naccu', 500);
    subplot(236)
    topoplot(cell2mat(pcond), chanlocs, ...
             'style', 'map', ...
             'electrodes', 'on', ...
             'shading', 'flat', ...
             'whitebk', 'off');
    caxis([0 0.05])
end
