% use std_chantopo

topoOpt = {'style', 'map', ...
           'electrodes', 'on', ...
           'shading', 'flat', ...
           'whitebk', 'off'};
contrast = [1,2; 1,3; 2,3; 4,5; 4,6; 5,6];
pval = cell
