function setEEGLAB(eeglabPath)

% add eeglab path
addpath(genpath(eeglabPath));

pop_editoptions( 'option_storedisk', 0, ...
                 'option_savetwofiles', 1, ...
                 'option_saveversion6', 1, ...
                 'option_single', 0, ...
                 'option_memmapdata', 0, ...
                 'option_eegobject', 0, ...
                 'option_computeica', 1, ...
                 'option_scaleicarms', 1, ...
                 'option_rememberfolder', 1, ...
                 'option_donotusetoolboxes', 0, ...
                 'option_checkversion', 0, ...
                 'option_chat', 0);