function build_std(STUDY, ALLEEG, EEG, g, stdcmds, output_dir)

[STUDY ALLEEG] = std_editset(STUDY, ALLEEG, ...
                             'name', g.study_name, ...
                             'task', g.study_task, ...
                             'notes', g.study_notes, ...
                             'commands', stdcmds, ...
                             'updatedat', 'on');

STUDY = pop_savestudy(STUDY, EEG, 'filename', ...
                      g.study_name, 'filepath', ...
                      output_dir);
