function [STUDY, erp_data, erp_times] = compute_erp(STUDY, ALLEEG, chan_label)

% erp_data: { nconds * ngroups } [ times * subjects ]
[STUDY, erp_data, erp_times] = ...
    std_erpplot(STUDY, ALLEEG, ...
                'channels', chan_label, ...
                'noplot', 'on', ...
                'averagechan', 'on');
