function [STUDY, ersp_data, ersp_times, ersp_freqs] = ...
    compute_ersp(STUDY, ALLEEG, chan_labels, timerange)

if ~exist('chan_labels', 'var')
    error('You must input channel labels to export ersp.');
end

if ~exist('timerange', 'var')
   timerange = [];
end

[STUDY, ersp_data, ersp_times, ersp_freqs] = ...
    std_erspplot(STUDY, ALLEEG, ...
                'channels', chan_labels, ...
                'plotsubjects', 'off', ...
                'timerange', timerange, ...
                'plotmode', 'none', ...
                'subbaseline', 'off');


